### ISSUE TITLE
Customizing the width

### ISSUE THREAD

**Issue by SGB555** [KyberNetwork/kyberswap-widgets#17]
The documentation mentions the ability to customize the width, but the width property is not being accepted in the widget's props.

![WX20240116-104920@2x](https://github.com/KyberNetwork/kyberswap-widgets/assets/22334195/e2e063f4-4b81-4382-b96c-3963f6795f42)

<img width="876" alt="image" src="https://github.com/KyberNetwork/kyberswap-widgets/assets/22334195/a3fe9f61-dbd9-4b15-9404-f33dd8816d0c">

The width of the Wrapper component is also not being applied to the width property that may be passed in.

<img width="1103" alt="image" src="https://github.com/KyberNetwork/kyberswap-widgets/assets/22334195/833ae3f3-e5ef-4ddb-a278-295bc168cffe">

**Comment by viet-nv** [comment]
hi @SGB555, You can wrap the widget in a div and then add a CSS selector like this to customize the widget:
```
<div className="widget">
   <Widget />
</div>
```

```
.widget {
 > div {
     width: 32rem;
   }
}
```
